### ISSUE TITLE
Best Buy

### ISSUE THREAD

**Issue by kdbarton1s** [CovidBusinessList/CovidBusinessList.github.io#1]
From Best Buy to their email subscribers, sent 3/22/20
![CBB0AF0A-307F-414D-960F-4F5462B3B909](https://user-images.githubusercontent.com/24883399/77258707-64a2ec00-6c4a-11ea-8a0c-9ff351e3f128.jpeg)

**Comment by zeryl** [comment]
Added, thank you!
